### ISSUE TITLE
Consider type inference over type assertions 

### ISSUE THREAD

**Issue by Eyas** [keplersj/gatsby-theme-early-bird#150]
See https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html#assertion-considered-harmful

I was looking at https://github.com/keplersj/gatsby-theme-early-bird/blob/master/gatsby-theme-early-bird/src/components/BlogPostItem/index.tsx#L40-L52

the `as BlogPosting` means that we're not getting the full power of TypeScript's type checking there. In general, something like:

```ts
const posting: BlogPosting = { ... };  // Better
const posting = { ... } as BlogPosting;  // Worse
```

as the latter *asserts* the type (kind of similar to "downcasting", in that it casts to more specific types --like in the links-- but not totally irrelevant types).

The fix, here and elsewhere, is to either assign to a temporary, or use something like (shameless plug) [react-schemaorg](https://www.npmjs.com/package/react-schemaorg) which does exactly the same thing you're doing, but forces type checking.

**Comment by keplersj** [comment]
Thank you for commenting on that! Really informative and helpful. I implemented your tips in one of my [other Gatsby themes](https://github.com/keplersj/gatsby-theme-atom-service/commit/6b1082daca72a51c0a9ecda2db4fa10ad81f5c4d) and it worked really well. This then lead me to [fix a bug](https://github.com/keplersj/jest-serializer-json-ld-script/commit/b565405c099f23e9c90335e7cdc212491d927ef8) in the package I use to serialize LD+JSON data in Jest snapshots. Thank you!
